# generate a docker-compose.yml file to up a postgresql container
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bloidev
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: DashboardDB
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
